### ISSUE TITLE
Documentation overhaul master plan

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#110]
We are currently overhauling the documentation, and here's where we'll keep track of those efforts.  Items include (additions/edits welcome):

- [X] Enable RTD hosting of docs: done in #101 
- [X] Create a reasonably fleshed-out README: done in #109 
- [X] Create an example IPython notebook: done in #106 
- [x] Update Installation instructions once #115 merged: use pip
- [x] Flesh out docstrings.  Best way to approach this?  Module-by-module?  This includes both creating docstrings where there are none but also converting existing docstrings to proper Sphinx/RST syntax.  This also includes a doctest-compliant Examples section for every function and class.
- [x] Flesh out documentation outside of docstrings.  First step is deciding on overall structure.  [Xarray's docs](http://xarray.pydata.org/en/stable/) are very nice, should start by looking at them to see how we can emulate them.
- [x] Add more description text to the existing example notebook.
- [x] (Re-)introduce a sample main script that provides the user with out-of-the box ability to permute across Calc parameter settings.
- [ ] Create a YouTube video showing an example of submitting jobs via the main script, to show them firing off in parallel.

**Comment by spencerahill** [comment]
The main docs should include What's New and Contributors sections.  I think the latter especially will get people excited about contributing.

**Comment by spencerahill** [comment]
Closing this, as this has nearly all been taken care of in the v0.1-v0.1.2 releases.  A YouTube video is overkill for now.
