### ISSUE TITLE
v0.1.2 announcement emails

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#127]
Once we've got v0.1 available via conda-forge (see #112), we should make an announcement in as many places as we can.  Below are the ones that come to mind for me.  @spencerkclark any others?

- [x] pangeo mailing list
- [x] xarray mailing list
- [x] pyaos mailing list
- [x] Princteon AOS mailing lists
- [x] GFDL python mailing list
- [x] My twitter (@spencerahill)
- [x] climlist

**Comment by spencerkclark** [comment]
Does v0.1 ship with the code pre-#126?  As small as the changes are, without them the code is pretty broken for any calculations involving pressure (symptomatic of our lack of test coverage there...).  

I'm in the process of updating some of my object library and doing some calculations with the latest version (that's how I noticed the issues fixed in #126).  Do you think it might be worth holding off a few more days in case more bugs like this surface (and releasing an intermediate version with the bug fixes)?

**Comment by spencerkclark** [comment]
I'm sorry about this; the issues in #126 stem completely from my refactoring of ```__config__``` and ```internal_names``` in #90.

**Comment by spencerahill** [comment]
>Does v0.1 ship with the code pre-#126

> Do you think it might be worth holding off a few more days in case more bugs like this surface (and releasing an intermediate version with the bug fixes)?

Yes and yes.  So this will go into v0.1.1.  It has to be a formal PyPI and Github release to go on conda-forge.

No worries!  It happens, and that's on us collectively since we don't have sufficient tests in place to catch it.  Plus it was my suggestion to do `internal_names`, AND I missed it when I did the code review of your PR.

How hard will it be to write a unit test for this?  Were we premature in closing #22?  I would really like to get a test in that catches this.  We'll also need to add a what's new entry.

**Comment by spencerkclark** [comment]
@spencerahill once we merge #135, give me another chance to run some real calculations (maybe it would be good if you did as well) just to be absolutely sure there are no more glaring bugs.  Then we can go ahead with the announcement emails.

**Comment by spencerahill** [comment]
Yes, will do also.  Let's play with it through the end of this week; if no further critical problems are found then I'll submit to PyPI and conda-forge over the weekend or next week.  Will wait to do the announcements until we're uploaded to conda-forge.

**Comment by spencerahill** [comment]
I'll also take care of #124 before then; that's the last remaining blocker for v0.1.1

**Comment by spencerahill** [comment]
Waiting on the conda-forge CI to finish; once that is finished, will update the docs and the README "quickstart" to reflect that conda is the preferred installation method.  THEN we're ready to announce.

**Comment by spencerahill** [comment]
The conda-forge build worked as hoped.  However, the RTD builds problem is giving me pause.  I don't want our first advertised release to have out-of-date documentation.  So I think it's worth waiting until that's fixed.

Can also try to find a workaround if the RTD folks don't make some progress on it soon.

**Comment by spencerahill** [comment]
Fortunately RTD appears to be in the process of resolving this: https://github.com/rtfd/readthedocs.org/issues/2651#issuecomment-284799880

**Comment by spencerahill** [comment]
RTD fixed the problem, and doc builds are succeeding again.  So I will proceed with #147 and then the quickstart update and then *finally* we can roll out the announcements.

**Comment by spencerahill** [comment]
@spencerkclark let me know if you think I'm just getting cold feet, but I think we need one more iteration before blasting to the world, i.e. a v0.1.2 release.

Motivation: the main script is the primary way we intend for users to interface with aospy, yet there are several problems with it:

- [x] It currently doesn't even ship with aospy, c.f. #149 
- [x] The Examples page of the documentation doesn't show how to use it: #150
- [x] The script should come with an example object library that it works with out of the box: #151
- [x] The script includes a lot of logic that need not be exposed to the user in that way: #152

I feel that putting all of these in place would make the package much more enticing to new users.

Given the blog post that we have due by the end of the month, this still needs to get done pretty soon; I fully intend to have it released on PyPI and submitted to conda by the end of next week, leaving us two weeks with the package feature-locked during which to write the post.

Does this seem reasonable to you?  I am happy to do all of this; I think much of it will be pretty simple now that I've typed this all out.

**Comment by spencerkclark** [comment]
By all means -- I think #149 and #152 alone could be thought of as blockers.  It would be a major plus to improve the documentation / examples on how the current two users *typically use* aospy (#150 and #151), so I am all for doing this!

**Comment by spencerahill** [comment]
Ok cool.  Thanks for your feedback.  Will put together 1 or more PRs in the coming days.

**Comment by spencerahill** [comment]
@spencerkclark do you feel like we're good for the v0.1.2 release once #166 is done?  All other v0.1.2 items are done.

For the sake of the blogpost, probably should release either tomorrow (Thursday) or Friday

**Comment by spencerahill** [comment]
@spencerkclark Barring any objections, will do the v0.1.2 release later tonight.

**Comment by spencerkclark** [comment]
I agree; I think things are ready to go.

**Comment by spencerahill** [comment]
It is done!
